# Development environment reusing production and just adding mounts for docker-sync
version: "2"
services:
  rsyncapp:
    environment:
      RAILS_ENV: 'development'
    volumes:
      - rsync-sync:/var/www:nocopy # will be mounted on /var/www
  unison:
    volumes:
      - unison-sync:/app/code:nocopy # will be mounted on /app/code
volumes:
  rsync-sync:
    external: true
  unison-sync:
    external: true
